version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  assignees:
    - marekdedic
    - davidulus
    - kalich5
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  assignees:
    - marekdedic
    - davidulus
    - kalich5
