name: "WordPress version checker"
on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  wordpress-version-checker:
    runs-on: ubuntu-latest
    steps:
      - name: WordPress version checker
        uses: skaut/wordpress-version-checker@close-comment
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
